"""
tools/test_plan_exporter.py
B.L.A.S.T. Phase 3 (Tools): Multi-Format Deliverable Exporter
Converts test plan JSON into Microsoft Word (.docx), Excel (.xlsx), and Markdown (.md).
Adheres strictly to architecture/sop_template_export.md.
"""

import os
import json
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

NAVY_HEX = "1F4E79"
LIGHT_BLUE_HEX = "D9E1F2"
GRAY_HEX = "F2F2F2"

def set_cell_background(cell, fill_hex):
    tcPr = cell._element.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{fill_hex}"/>')
    tcPr.append(shd)

def export_docx(plan, output_filepath):
    """Exports test plan to a polished Microsoft Word (.docx) document."""
    doc = docx.Document()

    # Document Header / Title
    meta = plan.get("metadata", {})
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(f"TEST PLAN: {meta.get('product_name', 'System Application')}")
    title_run.font.name = "Segoe UI"
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)
    title_p.paragraph_format.space_after = Pt(4)

    sub_p = doc.add_paragraph()
    sub_run = sub_p.add_run(f"Project Key: {meta.get('project_key', 'N/A')}  |  Generated by Intelligent Test Planning Agent  |  Model: {meta.get('llm_model', 'AI')}")
    sub_run.font.name = "Segoe UI"
    sub_run.font.size = Pt(10)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    sub_p.paragraph_format.space_after = Pt(16)

    # Helper function for adding styled sections
    def add_section_header(title):
        h = doc.add_heading(level=1)
        run = h.add_run(title)
        run.font.name = "Segoe UI"
        run.font.size = Pt(14)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)
        h.paragraph_format.space_before = Pt(12)
        h.paragraph_format.space_after = Pt(6)

    # 1. Objective
    add_section_header("1. Objective")
    obj_p = doc.add_paragraph(plan.get("objective", "Validation of application functionality, stability, and release criteria."))
    obj_p.paragraph_format.line_spacing = 1.15

    # 2. Scope
    add_section_header("2. Scope")
    scope = plan.get("scope", {})
    doc.add_paragraph("In-Scope Functional Areas:").runs[0].font.bold = True
    for item in scope.get("inclusions", ["Core application features", "User workflows"]):
        doc.add_paragraph(f"• {item}", style="List Bullet")
    
    doc.add_paragraph("Out-of-Scope Items:").runs[0].font.bold = True
    for item in scope.get("exclusions", ["Load & Stress testing", "Unsupported third-party plugins"]):
        doc.add_paragraph(f"• {item}", style="List Bullet")

    # 3. Test Environments
    add_section_header("3. Test Environments")
    envs = plan.get("test_environments", [])
    if envs:
        tbl = doc.add_table(rows=1, cols=2)
        tbl.alignment = WD_TABLE_ALIGNMENT.CENTER
        hdr_cells = tbl.rows[0].cells
        hdr_cells[0].text = "Category"
        hdr_cells[1].text = "Specification / Version"
        set_cell_background(hdr_cells[0], NAVY_HEX)
        set_cell_background(hdr_cells[1], NAVY_HEX)
        for c in hdr_cells:
            for r in c.paragraphs[0].runs:
                r.font.bold = True
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

        for e in envs:
            row_cells = tbl.add_row().cells
            row_cells[0].text = e.get("category", "Environment")
            row_cells[1].text = e.get("specification", "")
            for c in row_cells:
                c.paragraphs[0].paragraph_format.space_after = Pt(3)

    # 4. Strategy
    add_section_header("4. Test Strategy & Automation Approach")
    strat = plan.get("test_strategy", {})
    doc.add_paragraph(f"Testing Types: {', '.join(strat.get('types', ['Functional', 'Smoke', 'Regression']))}")
    doc.add_paragraph(f"Automation Approach: {strat.get('automation_approach', 'Playwright framework for end-to-end flows.')}")

    # 5. Test Cases Table
    add_section_header("5. Detailed Test Cases")
    tcs = plan.get("test_cases", [])
    if tcs:
        tbl_tc = doc.add_table(rows=1, cols=7)
        tbl_tc.alignment = WD_TABLE_ALIGNMENT.CENTER
        tc_headers = ["ID", "Jira Key", "Title", "Type", "Priority", "Steps", "Expected Result"]
        for i, th in enumerate(tc_headers):
            cell = tbl_tc.rows[0].cells[i]
            cell.text = th
            set_cell_background(cell, NAVY_HEX)
            for r in cell.paragraphs[0].runs:
                r.font.bold = True
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                r.font.size = Pt(9)

        for tc in tcs:
            row = tbl_tc.add_row().cells
            row[0].text = tc.get("id", "")
            row[1].text = tc.get("jira_reference", "")
            row[2].text = tc.get("title", "")
            row[3].text = tc.get("type", "")
            row[4].text = tc.get("priority", "")
            row[5].text = tc.get("steps", "")
            row[6].text = tc.get("expected_result", "")
            for c in row:
                for r in c.paragraphs[0].runs:
                    r.font.size = Pt(8.5)

    # 6. Entry & Exit Criteria
    add_section_header("6. Entry & Exit Criteria")
    doc.add_paragraph("Entry Criteria:").runs[0].font.bold = True
    for item in plan.get("entry_criteria", ["Deployment to QA environment verified", "Test data available"]):
        doc.add_paragraph(f"• {item}", style="List Bullet")
    doc.add_paragraph("Exit Criteria:").runs[0].font.bold = True
    for item in plan.get("exit_criteria", ["100% test cases executed", "No Blocker/Critical defects open"]):
        doc.add_paragraph(f"• {item}", style="List Bullet")

    # 7. Risks & Mitigations
    add_section_header("7. Risks & Mitigations")
    risks = plan.get("risks_and_mitigations", [])
    if risks:
        tbl_r = doc.add_table(rows=1, cols=3)
        for i, th in enumerate(["Risk", "Impact", "Mitigation"]):
            cell = tbl_r.rows[0].cells[i]
            cell.text = th
            set_cell_background(cell, NAVY_HEX)
            for r in cell.paragraphs[0].runs:
                r.font.bold = True
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        for rk in risks:
            row = tbl_r.add_row().cells
            row[0].text = rk.get("risk", "")
            row[1].text = rk.get("impact", "")
            row[2].text = rk.get("mitigation", "")

    # 8. Approvals
    add_section_header("8. Approvals")
    approvals = plan.get("approvals", [])
    if approvals:
        tbl_a = doc.add_table(rows=1, cols=3)
        for i, th in enumerate(["Role", "Reviewer Name", "Status"]):
            cell = tbl_a.rows[0].cells[i]
            cell.text = th
            set_cell_background(cell, NAVY_HEX)
            for r in cell.paragraphs[0].runs:
                r.font.bold = True
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        for a in approvals:
            row = tbl_a.add_row().cells
            row[0].text = a.get("role", "")
            row[1].text = a.get("name", "Pending")
            row[2].text = a.get("status", "Pending Review")

    os.makedirs(os.path.dirname(output_filepath), exist_ok=True)
    doc.save(output_filepath)
    return output_filepath

def export_xlsx(plan, output_filepath, template_type="inbuilt"):
    """Exports test plan to a styled Excel (.xlsx) workbook."""
    wb = openpyxl.Workbook()

    navy_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    blue_sub = PatternFill(start_color="D9E1F2", end_color="D9E1F2", fill_type="solid")
    gray_fill = PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid")
    white_font = Font(name="Segoe UI", size=10, bold=True, color="FFFFFF")
    header_font = Font(name="Segoe UI", size=13, bold=True, color="FFFFFF")
    bold_font = Font(name="Segoe UI", size=10, bold=True)
    regular_font = Font(name="Segoe UI", size=9.5)
    thin_border = Border(
        left=Side(style="thin", color="D9D9D9"),
        right=Side(style="thin", color="D9D9D9"),
        top=Side(style="thin", color="D9D9D9"),
        bottom=Side(style="thin", color="D9D9D9")
    )

    # Sheet 1: Overview
    ws_ov = wb.active
    ws_ov.title = "Test Plan Overview"
    ws_ov.views.sheetView[0].showGridLines = True

    meta = plan.get("metadata", {})
    ws_ov.merge_cells("A1:F2")
    ws_ov["A1"].value = f"TEST PLAN SPECIFICATION: {meta.get('product_name', 'VWO')}"
    ws_ov["A1"].font = header_font
    ws_ov["A1"].fill = navy_fill
    ws_ov["A1"].alignment = Alignment(horizontal="center", vertical="center")

    row = 4
    ws_ov.cell(row=row, column=1, value="1. EXECUTIVE OBJECTIVE").font = Font(name="Segoe UI", size=11, bold=True, color="1F4E79")
    ws_ov.cell(row=row, column=1).fill = blue_sub
    ws_ov.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 1
    ws_ov.cell(row=row, column=1, value=plan.get("objective", "")).font = regular_font
    ws_ov.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 2

    # Scope
    ws_ov.cell(row=row, column=1, value="2. SCOPE INCLUSIONS & EXCLUSIONS").font = Font(name="Segoe UI", size=11, bold=True, color="1F4E79")
    ws_ov.cell(row=row, column=1).fill = blue_sub
    ws_ov.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 1
    scope = plan.get("scope", {})
    inclusions_str = "Inclusions: " + "; ".join(scope.get("inclusions", []))
    ws_ov.cell(row=row, column=1, value=inclusions_str).font = regular_font
    ws_ov.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 1
    exclusions_str = "Exclusions: " + "; ".join(scope.get("exclusions", []))
    ws_ov.cell(row=row, column=1, value=exclusions_str).font = regular_font
    ws_ov.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 2

    # Sheet 2: Test Cases
    ws_tc = wb.create_sheet(title="Test Cases")
    ws_tc.views.sheetView[0].showGridLines = True

    tc_headers = [
        "Test Case ID", "Jira Issue Key", "Module / Feature", "Test Case Title",
        "Test Type", "Priority", "Preconditions", "Test Steps",
        "Expected Result", "Execution Status", "Automation Framework"
    ]
    ws_tc.append(tc_headers)
    for col_idx in range(1, len(tc_headers) + 1):
        c = ws_tc.cell(row=1, column=col_idx)
        c.font = white_font
        c.fill = navy_fill
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for tc in plan.get("test_cases", []):
        ws_tc.append([
            tc.get("id", ""),
            tc.get("jira_reference", ""),
            tc.get("module", ""),
            tc.get("title", ""),
            tc.get("type", ""),
            tc.get("priority", ""),
            tc.get("preconditions", ""),
            tc.get("steps", ""),
            tc.get("expected_result", ""),
            tc.get("status", "Draft"),
            tc.get("automation", "Yes (Playwright)")
        ])

    for r in range(2, ws_tc.max_row + 1):
        for c in range(1, len(tc_headers) + 1):
            cell = ws_tc.cell(row=r, column=c)
            cell.font = regular_font
            cell.border = thin_border
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    # Sheet 3: Risks & Mitigations
    ws_rk = wb.create_sheet(title="Risks & Approvals")
    ws_rk.views.sheetView[0].showGridLines = True
    rk_headers = ["Risk Description", "Impact", "Mitigation Strategy"]
    ws_rk.append(rk_headers)
    for col_idx in range(1, len(rk_headers) + 1):
        c = ws_rk.cell(row=1, column=col_idx)
        c.font = white_font
        c.fill = navy_fill
        c.alignment = Alignment(horizontal="center", vertical="center")
    for rk in plan.get("risks_and_mitigations", []):
        ws_rk.append([rk.get("risk", ""), rk.get("impact", ""), rk.get("mitigation", "")])
    for r in range(2, ws_rk.max_row + 1):
        for c in range(1, len(rk_headers) + 1):
            cell = ws_rk.cell(row=r, column=c)
            cell.font = regular_font
            cell.border = thin_border

    # Adjust widths
    for ws in [ws_ov, ws_tc, ws_rk]:
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val_str = str(cell.value or "")
                if "\n" in val_str:
                    val_str = max(val_str.split("\n"), key=len)
                max_len = max(max_len, len(val_str))
            ws.column_dimensions[col_letter].width = min(max(max_len + 3, 14), 45)

    os.makedirs(os.path.dirname(output_filepath), exist_ok=True)
    wb.save(output_filepath)
    return output_filepath

def export_markdown(plan, output_filepath):
    """Exports test plan to Markdown (.md)."""
    meta = plan.get("metadata", {})
    md = f"""# 📋 Test Plan: {meta.get('product_name', 'System')}

**Project Key:** {meta.get('project_key', 'N/A')}  
**Sprint / Version:** {meta.get('sprint', 'N/A')}  
**Date:** {meta.get('generated_date', 'N/A')}  
**Engine:** {meta.get('llm_model', 'AI')}  

---

## 1. Objective
{plan.get('objective', '')}

---

## 2. Scope
### Inclusions
"""
    for inc in plan.get("scope", {}).get("inclusions", []):
        md += f"- {inc}\n"
    md += "\n### Exclusions\n"
    for exc in plan.get("scope", {}).get("exclusions", []):
        md += f"- {exc}\n"

    md += "\n---\n\n## 3. Test Cases\n\n"
    md += "| ID | Jira Key | Title | Type | Priority | Expected Result | Automation |\n"
    md += "|---|---|---|---|---|---|---|\n"
    for tc in plan.get("test_cases", []):
        md += f"| {tc.get('id')} | {tc.get('jira_reference')} | {tc.get('title')} | {tc.get('type')} | {tc.get('priority')} | {tc.get('expected_result')} | {tc.get('automation')} |\n"

    md += "\n---\n\n## 4. Entry & Exit Criteria\n"
    md += "### Entry Criteria\n"
    for e in plan.get("entry_criteria", []):
        md += f"- {e}\n"
    md += "\n### Exit Criteria\n"
    for e in plan.get("exit_criteria", []):
        md += f"- {e}\n"

    os.makedirs(os.path.dirname(output_filepath), exist_ok=True)
    with open(output_filepath, "w", encoding="utf-8") as f:
        f.write(md)
    return output_filepath
